version: '3'

services:
    nginx:
        image: nginx
        ports:
            - 8080:80
        
    redis:
        image: redis
        volumes:
            - ./nginx:/usr/share/nginx/html/
        expose: 
            - 6379